# Generated by Django 5.1.4 on 2025-02-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0012_userprofile_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('rate', 'Rate')], max_length=10)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_app.course')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
