# Generated by Django 5.1.4 on 2025-02-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0013_courseinteraction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user_id', 'course')},
        ),
    ]
