# Generated by Django 5.1.4 on 2025-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0015_userprofile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.CharField(default='Beginner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
