# Generated by Django 5.1.4 on 2025-03-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0017_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
